default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: alessandrochuy
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: alessandrochuy
  username: alessandrochuy
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: alessandrochuy_production
  username: alessandrochuy
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

  cable:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: alessandrochuy
    password: <%= ENV['DATABASE_PASSWORD'] %>
    database: cable_production
    host: localhost