default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: alessandrochuy
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: alessandrochuy
  username: alessandrochuy
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: alessandrochuy
  username: alessandrochuy
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
