default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: cantera-editores_development

test:
  <<: *default
  database: cantera-editores_test

production:
  adapter: postgresql
  encoding: unicode
  database: cantera_editores
  username: postgres
  password: <%= Rails.application.credentials.password %>
  host: <%= Rails.application.credentials.host %>
  port: 5432